### ISSUE TITLE
Pocket islands only works if the inner island object is not included in selection

### ISSUE THREAD

**Issue by JensDyvik** [leomcelroy/barkbeetlejs#11]
Selecting both objects likes this makes a pocket with errors:
![image](https://github.com/leomcelroy/barkbeetlejs/assets/6598148/68ff572a-911b-4af8-b311-377ba829cc98)

![image](https://github.com/leomcelroy/barkbeetlejs/assets/6598148/5db3afca-2c54-45c0-92e2-4ff6c3eb3988)

While selecting only the outer object creates a proper pocket with an island:
![image](https://github.com/leomcelroy/barkbeetlejs/assets/6598148/6637554d-a912-4214-b845-51c4204824d3)

![image](https://github.com/leomcelroy/barkbeetlejs/assets/6598148/e4aab59e-53df-4fde-9ffb-b1fdef79bdf0)

This is different logic than most 2D CAM software and feels counter intuitive. It also makes it is less nice to create pockets with multiple different depths within each other because of the sharp inner corner challenge and the need to sometimes make edges narrower than the milling bit.

**Proposed solution:**

- When a toolpath operation being calculated, all geometry that is not selected is ignored in the calculation
- If a user wants to have a pocket with an island they need to select both the inner and outer object.
- Support for an island within an island within an island would be nice

**Comment by JensDyvik** [comment]
Example of nicer corners with Clipper:

![image](https://github.com/leomcelroy/barkbeetlejs/assets/6598148/278fb6bc-8aa9-4e9d-9c4f-e5b22e4a2d78)

**Comment by leomcelroy** [comment]
Thanks for the nicely written issue. I've implemented this as described.
